### ISSUE TITLE
[Feature Request] Remove WAF association 

### ISSUE THREAD

**Issue by MikeSouza** [MikeSouza/serverless-associate-waf#1]
Implement removal of WAF association when performing `sls remove`.

**Comment by moshebs** [comment]
Hi,

I must be missing something, but why is it required to explicitly delete a resource you added to the stack? Isn't it being automatically deleted as part of deletion of the whole stack?

Thanks!

**Comment by MikeSouza** [comment]
> Hi,
> 
> I must be missing something, but why is it required to explicitly delete a resource you added to the stack? Isn't it being automatically deleted as part of deletion of the whole stack?
> 
> Thanks!

You bring up a good point.  In most cases the `sls remove` will result in the removal of the API Gateway stage/ REST API and therefore the WAF association if the stack being removed created it.

It possible to share an API Gateway across stacks using the `provider.apiGateway` configuration.  So if you have a second service that adds endpoints to another service which creates the API Gateway, and it’s the second service that adds the WAF association using this plugin, when you remove the second service stack, what would the expected behavior be?

Not sure this is even worth implementing now that I think about it more.

**Comment by moshebs** [comment]
@MikeSouza, Thanks for clarifying.
