### ISSUE TITLE
Support for WAFv2

### ISSUE THREAD

**Issue by andypmw** [MikeSouza/serverless-associate-waf#16]
Hello,

thanks for your plugin. 

AWS just launched new version of WAF, the `WAFv2`:
https://aws.amazon.com/blogs/aws/announcing-aws-managed-rules-for-aws-waf/

I can see that this plugin will query by WAF name:
https://github.com/MikeSouza/serverless-associate-waf/blob/3d821457ab657f2de7e0b3d57a370a7cf4a5104b/lib/index.js#L53

It is using this AWS SDK method:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/WAF.html#listWebACLs-property

This plugin won't find any WAFv2 ACLs... Need to update it using new `WAFv2` query method:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/WAFV2.html#listWebACLs-property

Do you have time to update the plugin in the near future?

Thank you.

**Comment by MikeSouza** [comment]
What behavior do you propose?

Most likely I'd add a configuration option so that you must specify if it is a v2 WAF.

**Comment by dbirks** [comment]
Just commenting to confirm that WAFv2 support was added in 1.2.0:
https://www.npmjs.com/package/serverless-associate-waf/v/1.2.0
