### ISSUE TITLE
[Feature Request] Support associating WAF by WAF Web ACL ID

### ISSUE THREAD

**Issue by iDVB** [MikeSouza/serverless-associate-waf#22]
```
custom:
  associateWaf:
    name: { Fn::ImportValue: "dev-wafacl" }
```
which in in CFN nets out to the resource name eg...
`1234a1a-a1b1-12a1-abcd-a123b123456`

**Comment by MikeSouza** [comment]
First off, you didn't read the README. Provide the name of the Web ACL. Login to your AWS Console, go to WAF Classic, find the name of the Web ACL in the Name column. Use that. The whole point of this plugin is so you don't have to care about the generated unique ID and import it. The plugin looks up this unique ID for you.

**Comment by iDVB** [comment]
Thanks for being so kind in your reply. 
In fact I did read the readme. It’s just confusing as CFN calls that id the “resource name”
> “Ref returns the resource name, such as 1234a”
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-waf-webacl.html

Also, I’m not sure it’s as apparent as you suggest that this is precisely what the plugin was designed for. The primary use case from what I can see is to have it edit the exist APIG resource updating it with the provided WAF. Something less easily done without a plugin. 

Having said that, I’d like to make a feature request that you could supply the WAF resource name or the console name and have it added either way. I prefer not to name my resources and instead refer to them with refs and importvalue.

**Comment by MikeSouza** [comment]
Then create a Feature Request. Not an Issue.

**Comment by MikeSouza** [comment]
You are free to submit a PR with this feature implemented or fork this plugin. I do not have the time nor desire to implement such use case.

**Comment by iDVB** [comment]
Sure thing, let me just go read your contrib docs to find out how you would like that done. Buddy. Relax. You’ll live longer.

**Comment by MikeSouza** [comment]
Just use common sense and general contribution best practices. Good luck.
