### ISSUE TITLE
Cannot disassociate Waf for version V2

### ISSUE THREAD

**Issue by mchrist13** [MikeSouza/serverless-associate-waf#26]
The code to disassociateWaf() was not operating correctly when we had associated a WAF with V2. From looking at the README, it says "Remove the associateWaf element from your custom configurtation" - but this is incorrect as then it will default to Regional
`this.wafVersion = `WAF${this.config.version || "Regional"}` //config.version can be one of [V2, Regional]`
So later in the code, it looks for a Waf here:
`const webACLForResource = await this.provider.request(this.wafVersion, 'getWebACLForResource', params)`
and comes back undefined due to looking it up by only the default waf version.

Workaround:
Remove the name field from the serverless element but keep the version field:
`    associateWaf:
        version: V2`
Suggestions:
A) change the readme to let the user know that they need to keep the element but remove the name
B) when getting the webACLForResource, if it is undefined try and get one of the other version to make sure both are undefined

**Comment by mikesouza** [comment]
Thanks. I've updated the README for now.
