### ISSUE TITLE
Not Associating Service with WAF

### ISSUE THREAD

**Issue by tfendt** [MikeSouza/serverless-associate-waf#8]
This currently is not working with our setup. We keep getting the error: Serverless: Unable to determine REST API ID

Has anyone encountered this before?

**Comment by chaitanya11** [comment]
Hi @tfendt  can you show your serverless.yml.

**Comment by tfendt** [comment]
@chaitanya11 Yep, here you go:

`service: account

plugins:
  - serverless-offline
  - serverless-plugin-git-variables
  - serverless-plugin-split-stacks
  - serverless-domain-manager
  - serverless-plugin-tracing
  - serverless-associate-waf

custom:
  version: "1"
  webpack: ../../webpack.config.js
  serverless-offline:
    port: 3000
  customDomain:
    certificateName: '${file(../../serverless.env.yml):${opt:stage}.CERTIFICATE_NAME}'
    domainName: '${file(../../serverless.env.yml):${opt:stage}.DOMAIN_NAME}'
    basePath: 'account'
    createRoute53Record: true
  associateWaf:
    name: waf-api-dev

package:
  exclude:
    - ./**
  include:
    - account/handler.js
    - account/metaHandler.js
    - swagger.yml

provider:
  tracing: true
  name: aws
  runtime: nodejs8.10
  endpointType: ${file(../../serverless.env.yml):${opt:stage}.ENDPOINT_TYPE}
  environment: ${file(../../serverless.env.yml):${opt:stage}, "dev"}
  region: ${file(../../serverless.env.yml):${opt:stage}.REGION}
  timeout: 300
  versionFunctions: false
  deploymentBucket: ${file(../../serverless.env.yml):${opt:stage}.AWS_ACCOUNT_ID}.${file(../../serverless.env.yml):${opt:stage}.REGION}.serverless.deploy.buckets
  stackTags:
    GIT_BRANCH: "${git:branch}"
    GIT_SHA1: "${git:sha1}"
  role: arn:aws:iam::${file(../../serverless.env.yml):${opt:stage}.AWS_ACCOUNT_ID}:role/${opt:stage}-ms-lambda-role
  credentials:
    accessKeyId: ${file(../../serverless.env.yml):${opt:stage}.DEPLOY_ACCESS_KEY}
    secretAccessKey: ${file(../../serverless.env.yml):${opt:stage}.DEPLOY_ACCESS_SECRET}

functions: ${file(../shared/build/slsFunctionLoader.js)}
`

**Comment by chaitanya11** [comment]
@tfendt  this happens because you are using `serverless-plugin-split-stacks`. To resolve error you can specify `restapiId` in `provider`.

**Comment by tfendt** [comment]
@chaitanya11 Unfortunately when I use that workaround it results in another error:
"The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ApiGatewayRestApi] in the Resources block of the template"

**Comment by chaitanya11** [comment]
@tfendt  can you try this plugin https://www.npmjs.com/package/serverless-associate-waf-with-apigateway-caching

**Comment by tfendt** [comment]
@chaitanya11 When I go to look at the source for that plugin it just takes me to this github page. The directions are also exactly the same as this plugin.

**Comment by tfendt** [comment]
I replaced all the entries of serverless-associate-waf with serverless-associate-waf-with-apigateway-caching and it built. 

However when I deploy I get the same error as before: 
Serverless: Unable to determine REST API ID

**Comment by chaitanya11** [comment]
> @chaitanya11 When I go to look at the source for that plugin it just takes me to this github page. The directions are also exactly the same as this plugin.

@tfendt  am not the author for that plugin, it just worked for us....

**Comment by chaitanya11** [comment]
> I replaced all the entries of serverless-associate-waf with serverless-associate-waf-with-apigateway-caching and it built.
> 
> However when I deploy I get the same error as before:
> Serverless: Unable to determine REST API ID

@tfendt  are you able to anything related to apigateway in your cloudformation stack resources section ?

**Comment by chaitanya11** [comment]
@tfendt  i just issued a PR #12 around this fix. Feel free to use it.

**Comment by tfendt** [comment]
@chaitanya11 Thanks! I will check it out. I was able to modify the other plugin you mentioned to get it working but your PR looks a little simpler so I will try that.

**Comment by tfendt** [comment]
@chaitanya11 I tried your change and it still gives the error: Serverless: Unable to determine REST API ID

I do see the api-gateway id listed as a stack output though. I'll debug to see where the issue is.

**Comment by tfendt** [comment]
Found the issue. The gateway is in the output but not listed in the resources. The current code uses the stack resources to look for the rest ID.

**Comment by tfendt** [comment]
I added the following and it now works:
`  async findStackOutputByLogicalId(stackName, logicalId) {
    const response = await this.provider.request('CloudFormation', 'describeStacks', { StackName: stackName })
    if (response.Stacks[0].Outputs) {
      for (let resourceSummary of response.Stacks[0].Outputs) {
        if (logicalId === resourceSummary.OutputKey) {
          return resourceSummary
        }
      }
    }
  }`

In the getRestApiId function I added the following above the last if statement to check the outputs of the stack:
`if (!stackResource) {
        this.serverless.cli.log(`RestApiId not found (split stacks plugin used?), checking stack outputs for RestApiId.`);
        const stackResource = await this.findStackOutputByLogicalId(stackName, REST_API_ID_KEY)
        if (stackResource && stackResource.OutputValue) {
            return stackResource.OutputValue
          }
    }`

**Comment by chaitanya11** [comment]
Awesome @tfendt please raise a PR so that other people also have this.

**Comment by tfendt** [comment]
@chaitanya11 PR raised: https://github.com/MikeSouza/serverless-associate-waf/pull/13

**Comment by tfendt** [comment]
@chaitanya11 are you able to merge it?
